import { useState, useRef } from 'react'
import { Lock, ShieldCheck } from 'lucide-react'
import Input from '../ui/Input'
import Button from '../ui/Button'

export default function MfaVerifyForm({ onSubmit, loading, onToggleBackupMode, useBackupCode }) {
  const [otpCodes, setOtpCodes] = useState(['', '', '', '', '', ''])
  const [backupCode, setBackupCode] = useState('')
  const otpRefs = useRef([])

  const handleOtpChange = (index, value) => {
    if (!/^\d*$/.test(value)) return

    const newCodes = [...otpCodes]
    newCodes[index] = value.slice(-1)
    setOtpCodes(newCodes)

    if (value && index < 5) {
      otpRefs.current[index + 1]?.focus()
    }
  }

  const handleOtpKeyDown = (index, e) => {
    if (e.key === 'Backspace' && !otpCodes[index] && index > 0) {
      otpRefs.current[index - 1]?.focus()
    }
  }

  const handleOtpPaste = (e) => {
    e.preventDefault()
    const pastedData = e.clipboardData.getData('text').trim().slice(0, 6)
    if (!/^\d+$/.test(pastedData)) return

    const newCodes = [...otpCodes]
    for (let i = 0; i < pastedData.length; i++) {
      newCodes[i] = pastedData[i]
    }
    setOtpCodes(newCodes)

    const focusIndex = Math.min(pastedData.length, 5)
    otpRefs.current[focusIndex]?.focus()
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    const code = useBackupCode ? backupCode.trim() : otpCodes.join('')
    onSubmit(code)
  }

  return (
    <div className="space-y-6">
      <div className="text-center">
        <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-fuchsia-50 dark:bg-fuchsia-950/20 ring-1 ring-fuchsia-200">
          <ShieldCheck className="h-6 w-6 text-fuchsia-600 dark:text-fuchsia-400 animate-pulse" />
        </div>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Two-Factor Authentication</h2>
        <p className="mt-1 text-sm text-slate-555 text-slate-500">
          {useBackupCode
            ? 'Enter a recovery backup code to log in.'
            : 'Enter the 6-digit code generated by your Authenticator app.'}
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-5">
        {!useBackupCode ? (
          <div className="flex justify-between gap-2" onPaste={handleOtpPaste}>
            {otpCodes.map((code, index) => (
              <input
                key={index}
                ref={(el) => (otpRefs.current[index] = el)}
                type="text"
                inputMode="numeric"
                pattern="[0-9]*"
                maxLength={1}
                value={code}
                onChange={(e) => handleOtpChange(index, e.target.value)}
                onKeyDown={(e) => handleOtpKeyDown(index, e)}
                className="h-12 w-12 rounded-xl border border-slate-200 text-center text-lg font-bold text-slate-900 outline-none focus:border-fuchsia-500 focus:ring-2 focus:ring-fuchsia-400/40 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-100"
              />
            ))}
          </div>
        ) : (
          <Input
            id="backupCode"
            label="Recovery Backup Code"
            value={backupCode}
            onChange={setBackupCode}
            placeholder="e.g. ABC123XYZ"
            icon={Lock}
            required
          />
        )}

        <Button type="submit" loading={loading} className="w-full">
          Verify Identity
        </Button>
      </form>

      <div className="text-center">
        <button
          type="button"
          onClick={onToggleBackupMode}
          className="text-xs font-semibold text-fuchsia-600 hover:text-fuchsia-700 hover:underline dark:text-fuchsia-400 cursor-pointer"
        >
          {useBackupCode ? 'Use authenticator code instead' : 'Use recovery backup code'}
        </button>
      </div>
    </div>
  )
}
